"""empty message

Revision ID: c1214fa47004
Revises: 51b9ae06068a
Create Date: 2020-07-22 16:30:16.073128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1214fa47004'
down_revision = '51b9ae06068a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column(
        'start_time', sa.DateTime(), nullable=True))
    op.drop_column('show', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column(
        'start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
